Update README.md
AdmiralLuckytiger/Baton-INGENIA pull request #1
Opened 2023-12-11 09:28 UTC by ruedich

2023-12-11 09:32 UTC, ruedich commented on README.md
> +Un palo con luces :) WAAAAAAOOUUMMMM
Gracias :)

2023-12-11 09:38 UTC, AdmiralLuckytiger requested changes
No es lo que buscamos en el README.md. Revisa el formato y el contenido.

2023-12-11 09:38 UTC, AdmiralLuckytiger commented on README.md
> +Un palo con luces :) WAAAAAAOOUUMMMM
Podría ser un cubo de Leds.

2023-12-11 09:57 UTC, closed without merging

2024-02-29 16:51 UTC, ruedich reviewed
AAAAAAAAAAAAAAAAAAAAAAAAAAA